/* generated by build_data.py - do not edit by hand */
window.SECTIONS_DATA = {
 "tiers": {
  "unified": "עלון אחיד לכל הכיתות",
  "tiered": "עלון מדורג לפי שכבות גיל (א'-ב' / ג'-ו')"
 },
 "maxPerTier": 4,
 "groups": [
  {
   "id": "torah",
   "title": "תורה ופרשת השבוע"
  },
  {
   "id": "stories",
   "title": "סיפורים וקומיקס"
  },
  {
   "id": "world",
   "title": "ידע, מדע וחיים"
  },
  {
   "id": "play",
   "title": "משחק ופעילות משפחתית"
  }
 ],
 "sections": [
  {
   "key": "dvar-torah",
   "name": "דבר תורה",
   "desc": "דבר תורה קצר על פרשת השבוע, בשפה של ילדים.",
   "group": "torah",
   "imgs": [
    "section-01"
   ],
   "sizes": [
    [
     587,
     602
    ]
   ]
  },
  {
   "key": "ma-baparasha",
   "name": "מה בפרשה",
   "desc": "תמצית הפרשה השבועית.",
   "group": "torah",
   "imgs": [
    "section-02"
   ],
   "sizes": [
    [
     611,
     721
    ]
   ]
  },
  {
   "key": "chidot",
   "name": "חידות לפרשה",
   "desc": "חידות מא' ועד ת' על הפרשה.",
   "group": "torah",
   "imgs": [
    "section-04"
   ],
   "sizes": [
    [
     595,
     676
    ]
   ]
  },
  {
   "key": "chidot-tmunot",
   "name": "חידות בתמונות",
   "desc": "חידה בתמונות על הפרשה.",
   "group": "torah",
   "imgs": [
    "section-03"
   ],
   "sizes": [
    [
     587,
     691
    ]
   ]
  },
  {
   "key": "tifzoret",
   "name": "תפזורת",
   "desc": "תפזורת מילים על פרשת השבוע.",
   "group": "torah",
   "imgs": [
    "section-17"
   ],
   "sizes": [
    [
     861,
     596
    ]
   ]
  },
  {
   "key": "yesh-li-musag",
   "name": "יש לי מושג",
   "desc": "שאלות ותשובות ביהדות.",
   "group": "torah",
   "imgs": [
    "section-18",
    "section-19"
   ],
   "sizes": [
    [
     900,
     536
    ],
    [
     647,
     737
    ]
   ]
  },
  {
   "key": "misaviv",
   "name": "מסביב לשולחן",
   "desc": "סיפור ושאלות לדיון משפחתי סביב שולחן השבת.",
   "group": "stories",
   "imgs": [
    "section-05"
   ],
   "recommended": true,
   "sizes": [
    [
     867,
     687
    ]
   ]
  },
  {
   "key": "zeh-kara",
   "name": "זה קרה באמת",
   "desc": "סיפור צדיקים קצר.",
   "group": "stories",
   "imgs": [
    "section-07",
    "section-06"
   ],
   "sizes": [
    [
     572,
     807
    ],
    [
     450,
     671
    ]
   ]
  },
  {
   "key": "hemshechim",
   "name": "סיפור בהמשכים",
   "desc": "סיפור הרפתקאות מאויר, פרק בכל שבוע.",
   "group": "stories",
   "imgs": [
    "section-08",
    "section-09"
   ],
   "sizes": [
    [
     657,
     737
    ],
    [
     662,
     812
    ]
   ]
  },
  {
   "key": "komiks",
   "name": "קומיקס",
   "desc": "קומיקס עם מסר ערכי.",
   "group": "stories",
   "imgs": [
    "section-12",
    "section-13"
   ],
   "sizes": [
    [
     687,
     737
    ],
    [
     661,
     817
    ]
   ]
  },
  {
   "key": "niflaot",
   "name": "נפלאות הבריאה",
   "desc": "הצצה לפלאי הטבע והבריאה.",
   "group": "world",
   "imgs": [
    "section-16"
   ],
   "sizes": [
    [
     617,
     827
    ]
   ]
  },
  {
   "key": "or-behaskala",
   "name": "אור בהשכלה",
   "desc": "הסבר מדעי פשוט לשאלות מהעולם שסביבנו.",
   "group": "world",
   "imgs": [
    "section-21"
   ],
   "sizes": [
    [
     900,
     557
    ]
   ]
  },
  {
   "key": "bari",
   "name": "בריא לדעת",
   "desc": "ידע קצר על בריאות ושמירה על הגוף.",
   "group": "world",
   "imgs": [
    "section-11",
    "section-10"
   ],
   "sizes": [
    [
     682,
     802
    ],
    [
     607,
     697
    ]
   ]
  },
  {
   "key": "kacha",
   "name": "ככה זה בחיים",
   "desc": "כישור חיים משמעותי, כל שבוע אחר.",
   "group": "world",
   "imgs": [
    "section-20"
   ],
   "sizes": [
    [
     642,
     617
    ]
   ]
  },
  {
   "key": "hevdelim",
   "name": "מצא את ההבדלים",
   "desc": "מוצאים את ההבדלים בין שתי תמונות.",
   "group": "play",
   "imgs": [
    "section-14"
   ],
   "sizes": [
    [
     685,
     792
    ]
   ]
  },
  {
   "key": "milta",
   "name": "מלתא דבדיחותא",
   "desc": "בדיחה קצרה.",
   "group": "play",
   "imgs": [
    "section-15"
   ],
   "sizes": [
    [
     682,
     227
    ]
   ]
  },
  {
   "key": "ma-laasot",
   "name": "מה לעשות",
   "desc": "הצעה לפעילות משפחתית.",
   "group": "play",
   "imgs": [
    "section-22"
   ],
   "sizes": [
    [
     611,
     687
    ]
   ]
  }
 ],
 "form": {
  "action": "https://docs.google.com/forms/d/e/1FAIpQLSdPANBLRiNeaZMfvZCAaIuNYWynpbkyM08vSdu7URK6Ef9IXA/formResponse",
  "entries": {
   "school": "entry.1309888151",
   "contactName": "entry.634297929",
   "structure": "entry.387763023",
   "sectionsUnified": "entry.187764112",
   "sectionsYoung": "entry.1814055414",
   "sectionsOld": "entry.133351392",
   "notes": "entry.1306453797",
   "requestKind": "entry.1538303324",
   "schoolId": "entry.318885257"
  }
 }
};
